DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS posts;


CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE locations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    lat1 REAL NOT NULL,
    lat2 REAL NOT NULL,
    lon1 REAL NOT NULL,
    lon2 REAL NOT NULL,
    category TEXT
);